[server]
enableStaticServing = true

[theme]
base = "dark"
primaryColor = "#3182CE"
backgroundColor = "#1A202C"
secondaryBackgroundColor = "#2D3748"
codeBackgroundColor = "#1A202C"
textColor = "#E2E8F0"
linkColor = "#3182CE"
borderColor = "#7c7c7c"
showWidgetBorder = true
baseRadius = "0.3rem"
buttonRadius = "full"
font = "sans serif"

[theme.sidebar]
backgroundColor = "#121212"
secondaryBackgroundColor = "#000000"
codeBackgroundColor = "#2a2a2a"
borderColor = "#696969"
